[package]
name = "tinyset"
version = "0.3.5"
authors = ["David Roundy <daveroundy@gmail.com>"]

description = "Size-optimized sets"
license = "MIT/Apache-2.0"
repository = "https://github.com/droundy/tinyset"
edition = "2018"

readme = "README.md"

[dev-dependencies]

quickcheck = "^0.4.1"
heapsize = "0.4.2"
proptest = "0.9.4"
easybench = { version = "1.0.0", git = "https://github.com/droundy/easybench-rs" }

[badges]
travis-ci = { repository = "droundy/tinyset" }
appveyor = { repository = "droundy/tinyset" }

[dependencies]
fnv = "^1.0.3"
rand = "^0.3.15"
itertools = "0.8.1"

[[bench]]
name = "bench"
harness = false
