[package]
name = "smallset"
version = "0.1.0"
authors = ["David Roundy <daveroundy@gmail.com>"]

description = "Sets optimized for small numbers of elements"
license = "MPL-2.0"
repository = "https://github.com/droundy/smallset"
