[package]
name = "tinyset"
version = "0.0.7"
authors = ["David Roundy <daveroundy@gmail.com>"]

description = "Size-optimized  sets for Copy elements"
license = "MPL-2.0"
repository = "https://github.com/droundy/tinyset"

[dev-dependencies]

rand = "^0.3.15"
quickcheck = "^0.4.1"

[badges]
travis-ci = { repository = "droundy/tinyset" }
appveyor = { repository = "droundy/tinyset" }

[dependencies]
fnv = "^1.0.3"
