[package]
name = "tinyset-bench"
version = "0.0.1"
authors = ["David Roundy <daveroundy@gmail.com>"]

[dependencies]

rand = "^0.3.15"

tinyset = { path = ".." }
smallset = "^0.1.0"
fnv = "^1.0.3"

ordermap = "^0.2.10"
flat_map = "^0.0.4"
