[package]
name = "david-set-bench"
version = "0.0.1"
authors = ["David Roundy <daveroundy@gmail.com>"]

[dependencies]

rand = "^0.3.15"

david-set = { path = ".." }
david_allocator = { path = "../david_allocator" }
