[package]
name = "tinyset-bench"
version = "0.0.1"
authors = ["David Roundy <daveroundy@gmail.com>"]

[dependencies]

rand = "^0.3.15"

tinyset = { path = ".." }
david_allocator = { path = "../david_allocator" }
smallset = "^0.1.0"
fnv = "^1.0.3"
